### ISSUE TITLE
When can this dataset can be downloaded?

### ISSUE THREAD

**Issue by bityangke** [metalbubble/moments_models#1]
Hi Bolei,
It is exciting to see this large video dataset and I want to try our model on this dataset. 
However, I can not find where to download this dataset. Have this dataset been released or is it still in preparation？

**Comment by alexandonian** [comment]
Hi Ke,

I have also been involved with the release of the Moments in Time Dataset. I have very recently updated the website where you can find instructions for downloading the dataset.

http://moments.csail.mit.edu/#download

Best,
Alex

**Comment by bityangke** [comment]
@alexandonian Thanks very much!
I have sent an e-mail to mmonfort@mit.edu.

**Comment by sudonto** [comment]
Hi @alexandonian ,

I have downloaded the dataset from the official link. I found that no test set available (only training and val data). Could you provide me the link to download the test data? Thank you.

**Comment by pribadihcr** [comment]
Hi @alexandonian,

I have submitted the form for download the data, but no response yet. is it the data still available?. Thanks
