### ISSUE TITLE
issue in str replace when loading model

### ISSUE THREAD

**Issue by jqueguiner** [metalbubble/moments_models#2]
python 2.7
root@16e6dd7bd439:/torch/moments_models# python test_model.py
Traceback (most recent call last):
  File "test_model.py", line 54, in <module>
    model = load_model(modelID, categories)
  File "test_model.py", line 31, in load_model
    state_dict = {str.replace(k,'module.',''): v for k,v in checkpoint['state_dict'].items()}
  File "test_model.py", line 31, in <dictcomp>
    state_dict = {str.replace(k,'module.',''): v for k,v in checkpoint['state_dict'].items()}
TypeError: descriptor 'replace' requires a 'str' object but received a 'unicode'

**Comment by metalbubble** [comment]
please switch to python36
