### ISSUE TITLE
Pre-recorded Streaming video

### ISSUE THREAD

**Issue by fapeci** [metalbubble/moments_models#5]
Due to having most of the videos on the web and not locally on the computer, do we have an ability to use test_video on such media ?

**Comment by alexandonian** [comment]
Hi fapeci,

Currently, users are expected to evaluate models locally on their own machines. At some point, the video frame data needs be loaded into your machine's memory for evaluation, and you are free to do that in anyway you would like.

If you are simply interested in evaluating videos you find on the web, there exists many command line utilities such as `wget` and `youtube-dl` that make it very easy to download videos from the web. For example, if I wanted to predict the action in this [juggling video](http://data.csail.mit.edu/soundnet/actions3/juggling/vine-hWJwDv3eK9B_1.mp4) I found on the [Moments Explore Page](http://moments.csail.mit.edu/explore.html), I could download and evaluate it using:
```
wget http://data.csail.mit.edu/soundnet/actions3/juggling/vine-hWJwDv3eK9B_1.mp4
python test_video.py --video_file vine-hWJwDv3eK9B_1.mp4
```
Of course, you could write more sophisticated scripts that automate some of this, but I'll leave that up to you :). Hope that helps!

Alex
